# Generated by Django 2.2 on 2019-04-15 08:28

from django.db import migrations

def create_groups(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    Group = apps.get_model("auth", "Group")
    GroupExtend = apps.get_model("meetings", "GroupExtend")
    director = Group.objects.create(name="Director")
    GroupExtend.objects.create(group=director,app_label="meetings")

    # content_id = ContentType.objects.filter(app_label="meetings",model="event")[0].id
    # permission =  Permission.objects.filter(content_type_id=content_id,codename="view_event")[0]
    # director.permissions.add(permission)

    # admin = Group.objects.create(name="Admin")
    # GroupExtend.objects.create(group=admin,app_label="meetings")
    # staff = Group.objects.create(name="Staff")
    # GroupExtend.objects.create(group=staff,app_label="meetings")

class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_auto_20190411_1441'),
    ]

    operations = [migrations.RunPython(create_groups),
    ]
