# Generated by Django 2.2 on 2019-04-24 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authsignup', '0001_initial'),
        ('chat', '0002_authuserchat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthUserChat',
        ),
        migrations.CreateModel(
            name='AuthUserChat',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
                'constraints': [],
            },
            bases=('authsignup.authuser',),
        ),
    ]
