# Generated by Django 2.2 on 2019-04-24 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_abstract_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Abstract',
        ),
    ]
