# Generated by Django 2.2 on 2019-04-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, max_length=200, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='event',
            name='conference_bridge_number',
            field=models.CharField(blank=True, max_length=200, verbose_name='Conference Bridge No.'),
        ),
        migrations.AddField(
            model_name='event',
            name='custom_message',
            field=models.CharField(blank=True, max_length=200, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='exectime',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='pin',
            field=models.CharField(blank=True, max_length=50, verbose_name='Meeting PIN'),
        ),
        migrations.AddField(
            model_name='event',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='Publish'),
        ),
        migrations.AddField(
            model_name='event',
            name='street',
            field=models.CharField(blank=True, max_length=50, verbose_name='Street'),
        ),
        migrations.AddField(
            model_name='event',
            name='zip',
            field=models.CharField(blank=True, max_length=500, verbose_name='Zip'),
        ),
    ]
