# Generated by Django 2.2 on 2019-05-03 10:22

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_auto_20190502_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Meeting', 'verbose_name_plural': 'Meetings'},
        ),
        migrations.AddField(
            model_name='event',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.CharField(blank=True, max_length=200, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='topic',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='lead',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
