# Generated by Django 2.2 on 2019-04-15 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_admin_director_group_groupextend_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupextend',
            name='group',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
