# Generated by Django 2.2 on 2019-04-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_auto_20190429_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='archived',
            field=models.BooleanField(default=None, verbose_name='Archived'),
        ),
    ]
