# Generated by Django 2.2 on 2019-04-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0008_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admin_cell_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='admin_email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='admin_fax',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='admin_first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='admin_last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='admin_nick_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='admin_work_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='board_joining_date',
            field=models.DateField(blank=True, null=True, verbose_name='board joining date'),
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='disability',
            field=models.IntegerField(blank=True, choices=[(1, 'Yes'), (2, 'No'), (3, 'I decline to answer')], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ethinicity',
            field=models.IntegerField(blank=True, choices=[(1, 'Hispanic or Latino'), (2, 'American Indian or Alaskan Native'), (3, 'Asian'), (4, 'Native Hawaiian or Other Native Pacific Islander'), (5, 'Black or African American'), (6, 'White'), (7, 'Two or more races'), (8, 'I decline to answer')], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fax',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, 'Other'), (4, 'I decline to answer')], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_title',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='mail_to_assistant',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='nick_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='term_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='term_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='veteran',
            field=models.IntegerField(blank=True, choices=[(1, 'Yes'), (2, 'No'), (3, 'I decline to answer')], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='work_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
