# Generated by Django 2.2 on 2019-04-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0010_event_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='conference_bridge_number',
            field=models.CharField(default=None, max_length=200, verbose_name='Conference Bridge No.'),
        ),
    ]
