# Generated by Django 2.2 on 2019-04-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0010_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile/ETjUSr1v2n.png', null=True, upload_to='profile/'),
        ),
    ]
