# Generated by Django 2.2 on 2019-04-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0011_auto_20190418_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admin_image',
            field=models.ImageField(default='profile/ETjUSr1v2n.png', null=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='signature_image',
            field=models.ImageField(null=True, upload_to='profile/'),
        ),
    ]
