# Generated by Django 2.2 on 2019-04-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0012_auto_20190429_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='event',
            name='archived',
            field=models.BooleanField(default=None, null=True, verbose_name='Archived'),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(max_length=200, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='event',
            name='conference_bridge_number',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='Conference Bridge No.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='customMessage',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_call',
            field=models.BooleanField(default=None, null=True, verbose_name='End-Call On Moderator Left'),
        ),
        migrations.AlterField(
            model_name='event',
            name='exectime',
            field=models.DurationField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='password',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pin',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Meeting PIN'),
        ),
        migrations.AlterField(
            model_name='event',
            name='publish',
            field=models.BooleanField(default=None, null=True, verbose_name='Publish'),
        ),
        migrations.AlterField(
            model_name='event',
            name='street',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='event',
            name='zip',
            field=models.CharField(default=None, max_length=500, null=True, verbose_name='Zip'),
        ),
    ]
