# Generated by Django 2.2 on 2019-04-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0012_auto_20190418_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('users', models.ManyToManyField(blank=True, related_name='committees', to='meetings.Profile')),
            ],
        ),
    ]
