# Generated by Django 2.2 on 2019-04-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0014_profile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(to='meetings.User'),
        ),
    ]
