# Generated by Django 2.2 on 2019-04-12 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VotingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Voting Type')),
            ],
        ),
        migrations.CreateModel(
            name='VotingChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Choice')),
                ('voting_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.VotingType')),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Title')),
                ('open_date', models.DateTimeField(verbose_name='Start Date')),
                ('close_date', models.DateTimeField(verbose_name='End Date')),
                ('description', models.CharField(max_length=1000)),
                ('voting_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.VotingType')),
            ],
        ),
    ]
