# Generated by Django 2.2 on 2019-04-25 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votinganswer',
            name='answer',
        ),
    ]
