# Generated by Django 2.2 on 2019-04-30 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votinganswer',
            name='voting_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.VotingType'),
        ),
    ]
