# Generated by Django 2.2 on 2019-04-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_auto_20190412_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votingchoice',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='votingtype',
            name='voting_type',
        ),
        migrations.AddField(
            model_name='votingchoice',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Voting Choice'),
        ),
        migrations.AddField(
            model_name='votingtype',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Voting Type'),
        ),
    ]
