# Generated by Django 2.2 on 2019-04-30 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_votinganswer_voting_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votinganswer',
            name='voting_type',
        ),
    ]
