# Generated by Django 2.2 on 2019-05-02 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_remove_votinganswer_voting_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votinganswer',
            name='voting',
        ),
    ]
