# Generated by Django 2.2 on 2019-05-02 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_remove_votinganswer_voting'),
    ]

    operations = [
        migrations.AddField(
            model_name='votinganswer',
            name='voting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.Voting'),
        ),
    ]
