# Generated by Django 2.2 on 2019-04-12 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_votinganswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='user',
        ),
    ]
