# Generated by Django 2.2 on 2019-04-12 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_remove_voting_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='votinganswer',
            name='voting',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='voting.Voting'),
        ),
    ]
