# Generated by Django 2.2 on 2019-04-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_votinganswer_voting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votingchoice',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Voting Choice'),
        ),
        migrations.AlterField(
            model_name='votingtype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Voting Type'),
        ),
    ]
