# Generated by Django 2.2 on 2019-04-12 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_auto_20190412_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votinganswer',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.Voting'),
        ),
    ]
