# Generated by Django 2.2 on 2019-04-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_auto_20190416_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='enable_discussion',
            field=models.BooleanField(blank=True, default=False, verbose_name='Enable Discussion'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='signature_required',
            field=models.BooleanField(blank=True, default=False, verbose_name='Signature Required'),
        ),
    ]
