# Generated by Django 2.2 on 2019-04-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0011_auto_20190416_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='votinganswer',
            name='signature_data',
            field=models.BinaryField(blank=True, verbose_name='Signature Data'),
        ),
    ]
