# Generated by Django 2.2 on 2019-04-22 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0015_event_attendees'),
        ('voting', '0012_votinganswer_signature_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='meeting',
            field=models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, to='meetings.Event'),
        ),
    ]
