# Generated by Django 2.2 on 2019-04-22 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0015_event_attendees'),
        ('voting', '0013_voting_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='topic',
            field=models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, to='meetings.Topic'),
        ),
    ]
