# Generated by Django 2.2 on 2019-04-22 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0014_voting_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='topic',
        ),
    ]
