# Generated by Django 2.2 on 2019-04-22 11:58

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0015_event_attendees'),
        ('voting', '0015_remove_voting_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='topic',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='meeting', chained_model_field='event', default=False, on_delete=django.db.models.deletion.CASCADE, to='meetings.Topic'),
        ),
    ]
