# Generated by Django 2.2 on 2019-04-22 12:49

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0016_voting_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='topic',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='meeting', chained_model_field='meeting', default=False, on_delete=django.db.models.deletion.CASCADE, to='meetings.Topic'),
        ),
    ]
