# Generated by Django 2.2 on 2019-04-22 13:01

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0017_auto_20190422_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='topic',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='meeting', chained_model_field='event', on_delete=django.db.models.deletion.CASCADE, to='meetings.Topic'),
        ),
    ]
