# Generated by Django 2.2 on 2019-04-22 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0018_auto_20190422_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='topic',
            field=models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, to='meetings.Topic'),
        ),
    ]
