# Generated by Django 2.2 on 2019-05-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('html', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=30)),
                ('attachment', models.FileField(upload_to='files/')),
                ('pdf_doc', models.FileField(upload_to='converted/')),
                ('original_pdf', models.FileField(upload_to='original/')),
            ],
        ),
    ]
