# Generated by Django 2.2 on 2019-04-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='original_pdf',
            field=models.FileField(upload_to='original/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='pdf_doc',
            field=models.FileField(upload_to='converted/'),
        ),
    ]
