# Generated by Django 2.1.4 on 2018-12-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Username', models.CharField(max_length=250)),
                ('Password', models.TextField(max_length=250)),
                ('Date', models.DateTimeField()),
                ('Status', models.IntegerField()),
                ('Type', models.IntegerField()),
            ],
        ),
    ]
