# Generated by Django 2.1.4 on 2018-12-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogs',
            name='Status',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='userlogs',
            name='Type',
            field=models.CharField(choices=[('Login', 'Login'), ('ReLogin', 'Relogin')], default='Login', max_length=7),
        ),
    ]
