# Generated by Django 2.1.4 on 2018-12-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_view', '0003_auto_20181226_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogs',
            name='Status',
            field=models.IntegerField(choices=[(0, 'User Newely Created'), (1, 'User Activated'), (2, 'Regenerated Activation Link')], default=1),
        ),
    ]
