# Generated by Django 2.1.4 on 2018-12-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_view', '0004_auto_20181226_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogs',
            name='Password',
            field=models.TextField(max_length=50),
        ),
    ]
