# Generated by Django 2.1.4 on 2018-12-26 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_view', '0006_auto_20181226_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogs',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
