# Generated by Django 2.1.4 on 2018-12-26 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_view', '0007_auto_20181226_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogs',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='userlogs',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='userlogs',
            name='Username',
        ),
        migrations.AddField(
            model_name='userlogs',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
