# Generated by Django 2.1.4 on 2018-12-26 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_view', '0009_auto_20181226_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogs',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='userlogs',
            name='Status',
        ),
    ]
