# Generated by Django 2.1.4 on 2018-12-26 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_view', '0010_auto_20181226_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogs',
            old_name='user',
            new_name='user_id',
        ),
    ]
