# Generated by Django 2.1.4 on 2018-12-26 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_view', '0011_auto_20181226_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogs',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='UserLogs',
        ),
    ]
