# Generated by Django 2.1.4 on 2018-12-26 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_view', '0013_userlogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogs123',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username_id', models.CharField(max_length=250)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userlogs',
            name='author_id',
        ),
        migrations.DeleteModel(
            name='UserLogs',
        ),
    ]
