# Generated by Django 2.1.4 on 2018-12-26 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_view', '0015_auto_20181226_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogs123',
            old_name='Username_id',
            new_name='Unamet',
        ),
    ]
