# Generated by Django 2.1.4 on 2018-12-26 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_view', '0017_auto_20181226_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogs123',
            name='author_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
