# Generated by Django 2.1.4 on 2018-12-26 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_view', '0018_auto_20181226_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogs123',
            name='author_id',
        ),
        migrations.AddField(
            model_name='userlogs123',
            name='userff',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
