# Generated by Django 2.1.4 on 2018-12-26 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_view', '0019_auto_20181226_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogs123',
            old_name='userff',
            new_name='user',
        ),
    ]
