# Generated by Django 2.1.4 on 2018-12-26 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_view', '0020_auto_20181226_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogs123',
            name='user',
        ),
        migrations.AddField(
            model_name='userlogs123',
            name='user_id',
            field=models.OneToOneField(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
