# Generated by Django 2.1.4 on 2018-12-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_view', '0022_auto_20181226_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RollNo', models.IntegerField()),
                ('FirstName', models.CharField(max_length=250)),
                ('LastName', models.CharField(max_length=250)),
                ('standard', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='UserLog',
        ),
    ]
