# Generated by Django 2.1.4 on 2018-12-26 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_view', '0023_auto_20181226_1923'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
