# Generated by Django 2.1.4 on 2018-12-27 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_view', '0025_userlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlog',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='UserLog',
        ),
    ]
