# Generated by Django 2.1.4 on 2018-12-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_view', '0027_userlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlog',
            name='Email',
        ),
        migrations.AlterField(
            model_name='userlog',
            name='Status',
            field=models.IntegerField(choices=[(0, 'Activation Link'), (1, 'Expired Link')], default=0),
        ),
    ]
