# Generated by Django 2.1.4 on 2018-12-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_view', '0028_auto_20181227_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='Type',
            field=models.IntegerField(choices=[(0, 'Email'), (0, 'SMS')], default=0),
        ),
    ]
