# Generated by Django 2.1.4 on 2018-12-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_view', '0029_userlog_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlog',
            name='Type',
        ),
        migrations.AddField(
            model_name='userlog',
            name='AuthCode',
            field=models.CharField(default='abcd', max_length=4),
        ),
    ]
