# Generated by Django 2.1.4 on 2018-12-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_view', '0031_requesttable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttable',
            name='Status',
            field=models.IntegerField(choices=[(0, 'UnSolved'), (1, 'Solved')], default=0),
        ),
    ]
