# Generated by Django 2.1.4 on 2019-01-03 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_view', '0032_auto_20181231_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='requesttable',
            name='Status',
            field=models.IntegerField(choices=[(0, 'Solved'), (1, 'UnSolved')], default=0),
        ),
    ]
