# Generated by Django 2.1.4 on 2019-01-03 13:50

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('auth_view', '0033_auto_20190103_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userphone',
            name='PhoneNumber',
        ),
        migrations.AddField(
            model_name='userphone',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=1234567891011, max_length=128),
        ),
    ]
