# Generated by Django 2.2 on 2019-04-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_view', '0035_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='auth_destination',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='auth_destinationauth_destination',
            field=models.IntegerField(choices=[(1, 'Phone'), (2, 'Email')], default=1),
        ),
    ]
