# Generated by Django 2.2 on 2019-04-12 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_view', '0036_auto_20190412_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='auth_destinationauth_destination',
            new_name='auth_destination',
        ),
    ]
